# HTTP METHODS
GET = "GET"
POST = "POST"

# PATHS
PATH_FILES_UPSERT = "/files/upsert"
PATH_FILES = "/files"

# REQUEST
REQUEST_HTTP_METHOD = "httpMethod"
REQUEST_HEADERS = "headers"
REQUEST_API_KEY = "apikey"
REQUEST_PATH = "path"
REQUEST_BODY = "body"
REQUEST_BODY_FILTER = "filter"
REQUEST_BODY_FILE = "file"

# RESPONSE
RESPONSE_BODY = "body"
RESPONSE_STATUS = "statusCode"
